namespace PersonalLibrary.Services
{
    public class LocalizationService
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        private static readonly Dictionary<string, Dictionary<string, string>> _translations = new()
        {
            ["en"] = new()
            {
                ["Pager_Label"]          = "Pages",
                ["Pager_Prev"]           = "Previous",
                ["Pager_Next"]           = "Next",
                ["Pager_Info"]           = "{0}–{1} of {2}",
                ["Nav_Logout"]           = "Log out",
                ["Login_Title"]          = "Sign in",
                ["Login_Username"]       = "Username",
                ["Login_Password"]       = "Password",
                ["Login_Remember"]       = "Remember me",
                ["Login_Submit"]         = "Sign in",
                ["Login_Invalid"]        = "Wrong username or password.",
                ["Login_LockedOut"]      = "Too many failed attempts. Try again in {0} min.",
                ["Login_NotConfigured"]  = "Protection is enabled, but no username or password is set in protection.json.",
                ["Nav_Catalogue"]        = "Catalogue",
                ["Nav_MissingBooks"]     = "Missing Books",
                ["Nav_History"]          = "History",
                ["Nav_Trash"]            = "Trash",
                ["Page_Catalogue"]       = "Catalogue",
                ["Btn_AddAuthor"]        = "Add Author",
                ["Stat_Authors"]         = "Authors",
                ["Stat_Series"]          = "Series",
                ["Stat_Books"]           = "Books",
                ["Btn_BackToTop"]        = "Back to top",
                ["Search_Placeholder"]   = "Search authors, books, series...",
                ["Search_Results"]       = "Search Results",
                ["Search_NoResults"]     = "Nothing found for",
                ["Catalogue_Empty"]      = "The catalogue is empty. Add your first author!",
                ["Label_Author"]         = "Author",
                ["Label_Series"]         = "Series",
                ["Label_Book"]           = "Book",
                ["Author_AddTitle"]      = "Add Author",
                ["Author_Name"]          = "Name",
                ["Author_Photo"]         = "Photo (optional)",
                ["Author_DateAdded"]     = "Added",
                ["Author_Books"]         = "Books",
                ["Author_Series"]        = "Series",
                ["Author_Delete"]        = "Delete Author",
                ["Author_AddBook"]       = "Add Book",
                ["Author_AddSeries"]     = "Add Series",
                ["Author_NoBooksOrSeries"] = "No books or series yet.",
                ["Author_ConfirmDelete"] = "Are you sure you want to delete this author?",
                ["Author_AlreadyExists"] = "Author with this name already exists.",
                ["Book_Title"]           = "Title",
                ["Book_Cover"]           = "Cover (optional)",
                ["Book_AddTitle"]        = "Add Book",
                ["Book_Rename"]          = "Rename",
                ["Book_Delete"]          = "Delete Book",
                ["Book_ConfirmDelete"]   = "Are you sure you want to delete this book?",
                ["Book_Author"]          = "Author",
                ["Book_Type"]            = "Type: Book",
                ["Book_DateAdded"]       = "Added",
                ["Book_NewTitle"]        = "New title",
                ["Book_AlreadyExists"]   = "A book with this title already exists.",
                ["Book_SelectFile"]      = "Choose image...",
                ["Book_MissingHint"]     = "Use \"-\" to mark a missing book as placeholder",
                ["Book_TitlePlaceholder"] = "Book title",
                ["Book_OrderPlaceholder"] = "Leave empty — adds to the end",
                ["Series_Name"]          = "Series Name",
                ["Series_AddTitle"]      = "Add Series",
                ["Series_Rename"]        = "Rename",
                ["Series_Delete"]        = "Delete Series",
                ["Series_ConfirmDelete"] = "Are you sure you want to delete this series?",
                ["Series_Type"]          = "Type: Series",
                ["Series_Parts"]         = "Parts",
                ["Series_Part"]          = "Part",
                ["Series_PartsOptional"] = "Parts (optional)",
                ["Series_AddBook"]       = "Add Book to Series",
                ["Series_BookOrder"]     = "Position in series (optional)",
                ["Series_AddPart"]       = "Add Part",
                ["Series_Author"]        = "Author",
                ["Series_NewName"]       = "New name",
                ["Series_AlreadyExists"] = "A series with this name already exists.",
                ["Series_Cover"]         = "Series Cover (optional)",
                ["Series_NamePlaceholder"] = "Series name",
                ["Trash_Title"]          = "Trash",
                ["Trash_Empty"]          = "Trash is empty.",
                ["Trash_Clear"]          = "Clear Trash",
                ["Trash_ConfirmClear"]   = "Are you sure you want to permanently clear the trash?",
                ["Trash_Restore"]        = "Restore",
                ["Trash_DeleteForever"]  = "Delete Forever",
                ["Trash_Author"]         = "Author",
                ["Trash_Type"]           = "Type",
                ["Trash_Deleted"]        = "Deleted",
                ["Trash_AlreadyExists_Author"]  = "Cannot restore: author \"{0}\" already exists.",
                ["Trash_AlreadyExists_Series"]  = "Cannot restore: series \"{0}\" already exists for this author.",
                ["Trash_AlreadyExists_Book"]    = "Cannot restore: book \"{0}\" already exists for this author.",
                ["Trash_NoParentAuthor"]        = "Cannot restore: the parent author was also deleted.",
                ["History_Title"]        = "History",
                ["History_Empty"]        = "No actions recorded yet.",
                ["History_Clear"]        = "Clear History",
                ["History_ConfirmClear"] = "Are you sure you want to clear the history?",
                ["Hist_AuthorAdded"]     = "Author added: {0}",
                ["Hist_AuthorDeleted"]   = "Author deleted: {0} (with all books and series)",
                ["Hist_AuthorPhoto"]     = "Photo updated for author: {0}",
                ["Hist_BookAdded"]       = "Book added: \"{0}\" by {1}",
                ["Hist_BookAddedSeries"] = "Book added: \"{0}\" by {1} (series: {2})",
                ["Hist_BookDeleted"]     = "Book deleted: \"{0}\" by {1}",
                ["Hist_BookDeletedSeries"] = "Book deleted: \"{0}\" by {1} (series: {2})",
                ["Hist_BookRenamed"]     = "Book renamed: \"{0}\" → \"{1}\" by {2}",
                ["Hist_BookRenamedSeries"] = "Book renamed: \"{0}\" → \"{1}\" by {2} (series: {3})",
                ["Hist_BookCover"]       = "Cover updated for book: \"{0}\" by {1}",
                ["Hist_SeriesAdded"]     = "Series added: \"{0}\" by {1}",
                ["Hist_SeriesDeleted"]   = "Series deleted: \"{0}\" by {1} (with all books)",
                ["Hist_SeriesRenamed"]   = "Series renamed: \"{0}\" → \"{1}\" by {2}",
                ["Hist_SeriesCover"]     = "Cover updated for series: \"{0}\" by {1}",
                ["Hist_Restored"]        = "Restored from trash: {0} \"{1}\"",
                ["Hist_TrashCleared"]    = "Trash cleared",
                ["Hist_HistoryCleared"]  = "History cleared",
                ["Missing_Title"]        = "Missing Books",
                ["Missing_Empty"]        = "No missing books found. All series are complete!",
                ["Missing_Author"]       = "Author",
                ["Missing_Series"]       = "Series",
                ["Missing_Order"]        = "Position in series",
                ["Missing_Hint"]         = "Books with title \"-\" in any series appear here as placeholders.",
                ["Missing_Badge"]        = "missing",
                ["Confirm_Title"]        = "Confirm",
                ["Confirm_Cancel"]       = "Cancel",
                ["Confirm_Ok"]           = "Confirm",
                ["Btn_Save"]             = "Save",
                ["Btn_Cancel"]           = "Cancel",
                ["Btn_Delete"]           = "Delete",
                ["Btn_Confirm"]          = "Confirm",
                ["Btn_Close"]            = "Close",
                ["Month_01"] = "Jan", ["Month_02"] = "Feb", ["Month_03"] = "Mar",
                ["Month_04"] = "Apr", ["Month_05"] = "May", ["Month_06"] = "Jun",
                ["Month_07"] = "Jul", ["Month_08"] = "Aug", ["Month_09"] = "Sep",
                ["Month_10"] = "Oct", ["Month_11"] = "Nov", ["Month_12"] = "Dec",
            },

            ["ru"] = new()
            {
                ["Pager_Label"]          = "Страницы",
                ["Pager_Prev"]           = "Назад",
                ["Pager_Next"]           = "Вперёд",
                ["Pager_Info"]           = "{0}–{1} из {2}",
                ["Nav_Logout"]           = "Выйти",
                ["Login_Title"]          = "Вход",
                ["Login_Username"]       = "Логин",
                ["Login_Password"]       = "Пароль",
                ["Login_Remember"]       = "Запомнить меня",
                ["Login_Submit"]         = "Войти",
                ["Login_Invalid"]        = "Неверный логин или пароль.",
                ["Login_LockedOut"]      = "Слишком много неудачных попыток. Попробуйте через {0} мин.",
                ["Login_NotConfigured"]  = "Защита включена, но в protection.json не задан логин или пароль.",
                ["Nav_Catalogue"]        = "Каталог",
                ["Nav_MissingBooks"]     = "Недостающие книги",
                ["Nav_History"]          = "История",
                ["Nav_Trash"]            = "Корзина",
                ["Page_Catalogue"]       = "Каталог",
                ["Btn_AddAuthor"]        = "Добавить автора",
                ["Stat_Authors"]         = "Авторы",
                ["Stat_Series"]          = "Серии",
                ["Stat_Books"]           = "Книги",
                ["Btn_BackToTop"]        = "Наверх",
                ["Search_Placeholder"]   = "Поиск авторов, книг, серий...",
                ["Search_Results"]       = "Результаты поиска",
                ["Search_NoResults"]     = "Ничего не найдено по запросу",
                ["Catalogue_Empty"]      = "Каталог пуст. Добавьте первого автора!",
                ["Label_Author"]         = "Автор",
                ["Label_Series"]         = "Серия",
                ["Label_Book"]           = "Книга",
                ["Author_AddTitle"]      = "Добавить автора",
                ["Author_Name"]          = "Имя",
                ["Author_Photo"]         = "Фото (необязательно)",
                ["Author_DateAdded"]     = "Добавлен",
                ["Author_Books"]         = "Книги",
                ["Author_Series"]        = "Серии",
                ["Author_Delete"]        = "Удалить автора",
                ["Author_AddBook"]       = "Добавить книгу",
                ["Author_AddSeries"]     = "Добавить серию",
                ["Author_NoBooksOrSeries"] = "Пока нет книг или серий.",
                ["Author_ConfirmDelete"] = "Вы уверены, что хотите удалить этого автора?",
                ["Author_AlreadyExists"] = "Автор с таким именем уже существует.",
                ["Book_Title"]           = "Название",
                ["Book_Cover"]           = "Обложка (необязательно)",
                ["Book_AddTitle"]        = "Добавить книгу",
                ["Book_Rename"]          = "Переименовать",
                ["Book_Delete"]          = "Удалить книгу",
                ["Book_ConfirmDelete"]   = "Вы уверены, что хотите удалить эту книгу?",
                ["Book_Author"]          = "Автор",
                ["Book_Type"]            = "Тип: Книга",
                ["Book_DateAdded"]       = "Добавлена",
                ["Book_NewTitle"]        = "Новое название",
                ["Book_AlreadyExists"]   = "Книга с таким названием уже существует.",
                ["Book_SelectFile"]      = "Выбрать изображение...",
                ["Book_MissingHint"]     = "Используйте «-» для обозначения недостающей книги",
                ["Book_TitlePlaceholder"] = "Название книги",
                ["Book_OrderPlaceholder"] = "Пусто — добавится в конец",
                ["Series_Name"]          = "Название серии",
                ["Series_AddTitle"]      = "Добавить серию",
                ["Series_Rename"]        = "Переименовать",
                ["Series_Delete"]        = "Удалить серию",
                ["Series_ConfirmDelete"] = "Вы уверены, что хотите удалить эту серию?",
                ["Series_Type"]          = "Тип: Серия",
                ["Series_Parts"]         = "Части",
                ["Series_Part"]          = "Часть",
                ["Series_PartsOptional"] = "Части (необязательно)",
                ["Series_AddBook"]       = "Добавить книгу в серию",
                ["Series_BookOrder"]     = "Позиция в серии (необязательно)",
                ["Series_AddPart"]       = "Добавить часть",
                ["Series_Author"]        = "Автор",
                ["Series_NewName"]       = "Новое название",
                ["Series_AlreadyExists"] = "Серия с таким названием уже существует.",
                ["Series_Cover"]         = "Обложка серии (необязательно)",
                ["Series_NamePlaceholder"] = "Название серии",
                ["Trash_Title"]          = "Корзина",
                ["Trash_Empty"]          = "Корзина пуста.",
                ["Trash_Clear"]          = "Очистить корзину",
                ["Trash_ConfirmClear"]   = "Вы уверены, что хотите полностью очистить корзину?",
                ["Trash_Restore"]        = "Восстановить",
                ["Trash_DeleteForever"]  = "Удалить навсегда",
                ["Trash_Author"]         = "Автор",
                ["Trash_Type"]           = "Тип",
                ["Trash_Deleted"]        = "Удалено",
                ["Trash_AlreadyExists_Author"]  = "Невозможно восстановить: автор «{0}» уже существует.",
                ["Trash_AlreadyExists_Series"]  = "Невозможно восстановить: серия «{0}» уже существует у этого автора.",
                ["Trash_AlreadyExists_Book"]    = "Невозможно восстановить: книга «{0}» уже существует у этого автора.",
                ["Trash_NoParentAuthor"]        = "Невозможно восстановить: автор тоже был удалён.",
                ["History_Title"]        = "История",
                ["History_Empty"]        = "Действий пока не было.",
                ["History_Clear"]        = "Очистить историю",
                ["History_ConfirmClear"] = "Вы уверены, что хотите очистить историю?",
                ["Hist_AuthorAdded"]     = "Добавлен автор: {0}",
                ["Hist_AuthorDeleted"]   = "Удалён автор: {0} (со всеми книгами и сериями)",
                ["Hist_AuthorPhoto"]     = "Обновлено фото автора: {0}",
                ["Hist_BookAdded"]       = "Добавлена книга: «{0}» — {1}",
                ["Hist_BookAddedSeries"] = "Добавлена книга: «{0}» — {1} (серия: {2})",
                ["Hist_BookDeleted"]     = "Удалена книга: «{0}» — {1}",
                ["Hist_BookDeletedSeries"] = "Удалена книга: «{0}» — {1} (серия: {2})",
                ["Hist_BookRenamed"]     = "Переименована книга: «{0}» → «{1}» — {2}",
                ["Hist_BookRenamedSeries"] = "Переименована книга: «{0}» → «{1}» — {2} (серия: {3})",
                ["Hist_BookCover"]       = "Обновлена обложка книги: «{0}» — {1}",
                ["Hist_SeriesAdded"]     = "Добавлена серия: «{0}» — {1}",
                ["Hist_SeriesDeleted"]   = "Удалена серия: «{0}» — {1} (со всеми книгами)",
                ["Hist_SeriesRenamed"]   = "Переименована серия: «{0}» → «{1}» — {2}",
                ["Hist_SeriesCover"]     = "Обновлена обложка серии: «{0}» — {1}",
                ["Hist_Restored"]        = "Восстановлено из корзины: {0} «{1}»",
                ["Hist_TrashCleared"]    = "Корзина очищена",
                ["Hist_HistoryCleared"]  = "История очищена",
                ["Missing_Title"]        = "Недостающие книги",
                ["Missing_Empty"]        = "Недостающих книг нет. Все серии полные!",
                ["Missing_Author"]       = "Автор",
                ["Missing_Series"]       = "Серия",
                ["Missing_Order"]        = "Позиция в серии",
                ["Missing_Hint"]         = "Книги с названием «-» в любой серии отображаются здесь как недостающие.",
                ["Missing_Badge"]        = "нет",
                ["Confirm_Title"]        = "Подтверждение",
                ["Confirm_Cancel"]       = "Отмена",
                ["Confirm_Ok"]           = "Подтвердить",
                ["Btn_Save"]             = "Сохранить",
                ["Btn_Cancel"]           = "Отмена",
                ["Btn_Delete"]           = "Удалить",
                ["Btn_Confirm"]          = "Подтвердить",
                ["Btn_Close"]            = "Закрыть",
                ["Month_01"] = "янв", ["Month_02"] = "фев", ["Month_03"] = "мар",
                ["Month_04"] = "апр", ["Month_05"] = "май", ["Month_06"] = "июн",
                ["Month_07"] = "июл", ["Month_08"] = "авг", ["Month_09"] = "сен",
                ["Month_10"] = "окт", ["Month_11"] = "ноя", ["Month_12"] = "дек",
            },

            ["pl"] = new()
            {
                ["Pager_Label"]          = "Strony",
                ["Pager_Prev"]           = "Wstecz",
                ["Pager_Next"]           = "Dalej",
                ["Pager_Info"]           = "{0}–{1} z {2}",
                ["Nav_Logout"]           = "Wyloguj",
                ["Login_Title"]          = "Logowanie",
                ["Login_Username"]       = "Login",
                ["Login_Password"]       = "Hasło",
                ["Login_Remember"]       = "Zapamiętaj mnie",
                ["Login_Submit"]         = "Zaloguj",
                ["Login_Invalid"]        = "Nieprawidłowy login lub hasło.",
                ["Login_LockedOut"]      = "Zbyt wiele nieudanych prób. Spróbuj ponownie za {0} min.",
                ["Login_NotConfigured"]  = "Ochrona jest włączona, ale w protection.json nie ustawiono loginu ani hasła.",
                ["Nav_Catalogue"]        = "Katalog",
                ["Nav_MissingBooks"]     = "Brakujące książki",
                ["Nav_History"]          = "Historia",
                ["Nav_Trash"]            = "Kosz",
                ["Page_Catalogue"]       = "Katalog",
                ["Btn_AddAuthor"]        = "Dodaj autora",
                ["Stat_Authors"]         = "Autorzy",
                ["Stat_Series"]          = "Serie",
                ["Stat_Books"]           = "Książki",
                ["Btn_BackToTop"]        = "Na górę",
                ["Search_Placeholder"]   = "Szukaj autorów, książek, serii...",
                ["Search_Results"]       = "Wyniki wyszukiwania",
                ["Search_NoResults"]     = "Nic nie znaleziono dla",
                ["Catalogue_Empty"]      = "Katalog jest pusty. Dodaj pierwszego autora!",
                ["Label_Author"]         = "Autor",
                ["Label_Series"]         = "Seria",
                ["Label_Book"]           = "Książka",
                ["Author_AddTitle"]      = "Dodaj autora",
                ["Author_Name"]          = "Imię i nazwisko",
                ["Author_Photo"]         = "Zdjęcie (opcjonalnie)",
                ["Author_DateAdded"]     = "Dodano",
                ["Author_Books"]         = "Książki",
                ["Author_Series"]        = "Serie",
                ["Author_Delete"]        = "Usuń autora",
                ["Author_AddBook"]       = "Dodaj książkę",
                ["Author_AddSeries"]     = "Dodaj serię",
                ["Author_NoBooksOrSeries"] = "Brak książek lub serii.",
                ["Author_ConfirmDelete"] = "Czy na pewno chcesz usunąć tego autora?",
                ["Author_AlreadyExists"] = "Autor o tym imieniu już istnieje.",
                ["Book_Title"]           = "Tytuł",
                ["Book_Cover"]           = "Okładka (opcjonalnie)",
                ["Book_AddTitle"]        = "Dodaj książkę",
                ["Book_Rename"]          = "Zmień nazwę",
                ["Book_Delete"]          = "Usuń książkę",
                ["Book_ConfirmDelete"]   = "Czy na pewno chcesz usunąć tę książkę?",
                ["Book_Author"]          = "Autor",
                ["Book_Type"]            = "Typ: Książka",
                ["Book_DateAdded"]       = "Dodano",
                ["Book_NewTitle"]        = "Nowy tytuł",
                ["Book_AlreadyExists"]   = "Książka o takim tytule już istnieje.",
                ["Book_SelectFile"]      = "Wybierz obraz...",
                ["Book_MissingHint"]     = "Użyj «-» aby oznaczyć brakującą książkę",
                ["Book_TitlePlaceholder"] = "Tytuł książki",
                ["Book_OrderPlaceholder"] = "Puste — dodaje na końcu",
                ["Series_Name"]          = "Nazwa serii",
                ["Series_AddTitle"]      = "Dodaj serię",
                ["Series_Rename"]        = "Zmień nazwę",
                ["Series_Delete"]        = "Usuń serię",
                ["Series_ConfirmDelete"] = "Czy na pewno chcesz usunąć tę serię?",
                ["Series_Type"]          = "Typ: Seria",
                ["Series_Parts"]         = "Części",
                ["Series_Part"]          = "Część",
                ["Series_PartsOptional"] = "Części (opcjonalnie)",
                ["Series_AddBook"]       = "Dodaj książkę do serii",
                ["Series_BookOrder"]     = "Pozycja w serii (opcjonalnie)",
                ["Series_AddPart"]       = "Dodaj część",
                ["Series_Author"]        = "Autor",
                ["Series_NewName"]       = "Nowa nazwa",
                ["Series_AlreadyExists"] = "Seria o takiej nazwie już istnieje.",
                ["Series_Cover"]         = "Okładka serii (opcjonalnie)",
                ["Series_NamePlaceholder"] = "Nazwa serii",
                ["Trash_Title"]          = "Kosz",
                ["Trash_Empty"]          = "Kosz jest pusty.",
                ["Trash_Clear"]          = "Opróżnij kosz",
                ["Trash_ConfirmClear"]   = "Czy na pewno chcesz opróżnić kosz?",
                ["Trash_Restore"]        = "Przywróć",
                ["Trash_DeleteForever"]  = "Usuń na zawsze",
                ["Trash_Author"]         = "Autor",
                ["Trash_Type"]           = "Typ",
                ["Trash_Deleted"]        = "Usunięto",
                ["Trash_AlreadyExists_Author"]  = "Nie można przywrócić: autor «{0}» już istnieje.",
                ["Trash_AlreadyExists_Series"]  = "Nie można przywrócić: seria «{0}» już istnieje dla tego autora.",
                ["Trash_AlreadyExists_Book"]    = "Nie można przywrócić: książka «{0}» już istnieje dla tego autora.",
                ["Trash_NoParentAuthor"]        = "Nie można przywrócić: autor również został usunięty.",
                ["History_Title"]        = "Historia",
                ["History_Empty"]        = "Brak zapisanych działań.",
                ["History_Clear"]        = "Wyczyść historię",
                ["History_ConfirmClear"] = "Czy na pewno chcesz wyczyścić historię?",
                ["Hist_AuthorAdded"]     = "Dodano autora: {0}",
                ["Hist_AuthorDeleted"]   = "Usunięto autora: {0} (z wszystkimi książkami i seriami)",
                ["Hist_AuthorPhoto"]     = "Zaktualizowano zdjęcie autora: {0}",
                ["Hist_BookAdded"]       = "Dodano książkę: «{0}» — {1}",
                ["Hist_BookAddedSeries"] = "Dodano książkę: «{0}» — {1} (seria: {2})",
                ["Hist_BookDeleted"]     = "Usunięto książkę: «{0}» — {1}",
                ["Hist_BookDeletedSeries"] = "Usunięto książkę: «{0}» — {1} (seria: {2})",
                ["Hist_BookRenamed"]     = "Zmieniono nazwę książki: «{0}» → «{1}» — {2}",
                ["Hist_BookRenamedSeries"] = "Zmieniono nazwę książki: «{0}» → «{1}» — {2} (seria: {3})",
                ["Hist_BookCover"]       = "Zaktualizowano okładkę książki: «{0}» — {1}",
                ["Hist_SeriesAdded"]     = "Dodano serię: «{0}» — {1}",
                ["Hist_SeriesDeleted"]   = "Usunięto serię: «{0}» — {1} (z wszystkimi książkami)",
                ["Hist_SeriesRenamed"]   = "Zmieniono nazwę serii: «{0}» → «{1}» — {2}",
                ["Hist_SeriesCover"]     = "Zaktualizowano okładkę serii: «{0}» — {1}",
                ["Hist_Restored"]        = "Przywrócono z kosza: {0} «{1}»",
                ["Hist_TrashCleared"]    = "Kosz opróżniony",
                ["Hist_HistoryCleared"]  = "Historia wyczyszczona",
                ["Missing_Title"]        = "Brakujące książki",
                ["Missing_Empty"]        = "Brak brakujących książek. Wszystkie serie są kompletne!",
                ["Missing_Author"]       = "Autor",
                ["Missing_Series"]       = "Seria",
                ["Missing_Order"]        = "Pozycja w serii",
                ["Missing_Hint"]         = "Książki z tytułem «-» w dowolnej serii są wyświetlane tutaj jako brakujące.",
                ["Missing_Badge"]        = "brak",
                ["Confirm_Title"]        = "Potwierdź",
                ["Confirm_Cancel"]       = "Anuluj",
                ["Confirm_Ok"]           = "Potwierdź",
                ["Btn_Save"]             = "Zapisz",
                ["Btn_Cancel"]           = "Anuluj",
                ["Btn_Delete"]           = "Usuń",
                ["Btn_Confirm"]          = "Potwierdź",
                ["Btn_Close"]            = "Zamknij",
                ["Month_01"] = "sty", ["Month_02"] = "lut", ["Month_03"] = "mar",
                ["Month_04"] = "kwi", ["Month_05"] = "maj", ["Month_06"] = "cze",
                ["Month_07"] = "lip", ["Month_08"] = "sie", ["Month_09"] = "wrz",
                ["Month_10"] = "paź", ["Month_11"] = "lis", ["Month_12"] = "gru",
            }
        };

        public LocalizationService(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        public string CurrentCulture
        {
            get
            {
                var langCookie = _httpContextAccessor.HttpContext?.Request.Cookies["lang"];
                if (!string.IsNullOrEmpty(langCookie) && _translations.ContainsKey(langCookie))
                    return langCookie;

                var aspCookie = _httpContextAccessor.HttpContext?.Request.Cookies[".AspNetCore.Culture"];
                if (aspCookie != null)
                {
                    var uicPart = aspCookie.Split('|')
                        .FirstOrDefault(p => p.StartsWith("uic="))
                        ?.Replace("uic=", "");
                    if (!string.IsNullOrEmpty(uicPart) && _translations.ContainsKey(uicPart))
                        return uicPart;
                }
                return "en";
            }
        }

        public string this[string key]
        {
            get
            {
                var culture = CurrentCulture;
                if (_translations.TryGetValue(culture, out var dict) &&
                    dict.TryGetValue(key, out var value))
                    return value;
                if (_translations["en"].TryGetValue(key, out var fallback))
                    return fallback;
                return key;
            }
        }

        public string FormatDate(DateTime dt)
        {
            var month = this[$"Month_{dt.Month:D2}"];
            return $"{dt.Day:D2} {month} {dt.Year}";
        }
    }
}
