namespace PersonalLibrary.Services
{
    public class LocalizationService
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        private static readonly Dictionary<string, Dictionary<string, string>> _translations = new()
        {
            ["en"] = new()
            {
                ["Pager_Label"]          = "Pages",
                ["Pager_Prev"]           = "Previous",
                ["Pager_Next"]           = "Next",
                ["Pager_Info"]           = "{0}–{1} of {2}",
                ["Nav_Logout"]           = "Log out",
                ["Login_Title"]          = "Sign in",
                ["Login_Username"]       = "Username",
                ["Login_Password"]       = "Password",
                ["Login_Remember"]       = "Remember me",
                ["Login_Submit"]         = "Sign in",
                ["Login_Invalid"]        = "Wrong username or password.",
                ["Login_LockedOut"]      = "Too many failed attempts. Try again in {0} min.",
                ["Login_NotConfigured"]  = "Protection is enabled, but no username or password is set in protection.json.",
                ["Nav_Catalogue"]        = "Catalogue",
                ["Nav_MissingBooks"]     = "Missing Books",
                ["Nav_History"]          = "History",
                ["Nav_Trash"]            = "Trash",
                ["Page_Catalogue"]       = "Catalogue",
                ["Btn_AddAuthor"]        = "Add Author",
                ["Stat_Authors"]         = "Authors",
                ["Stat_Series"]          = "Series",
                ["Stat_Books"]           = "Books",
                ["Btn_BackToTop"]        = "Back to top",
                ["Search_Placeholder"]   = "Search authors, books, series...",
                ["Search_Results"]       = "Search Results",
                ["Search_NoResults"]     = "Nothing found for",
                ["Catalogue_Empty"]      = "The catalogue is empty. Add your first author!",
                ["Label_Author"]         = "Author",
                ["Label_Series"]         = "Series",
                ["Label_Book"]           = "Book",
                ["Author_AddTitle"]      = "Add Author",
                ["Author_Name"]          = "Name",
                ["Author_Photo"]         = "Photo (optional)",
                ["Author_DateAdded"]     = "Added",
                ["Author_Books"]         = "Books",
                ["Author_Series"]        = "Series",
                ["Author_Delete"]        = "Delete Author",
                ["Author_AddBook"]       = "Add Book",
                ["Author_AddSeries"]     = "Add Series",
                ["Author_NoBooksOrSeries"] = "No books or series yet.",
                ["Author_ConfirmDelete"] = "Are you sure you want to delete this author?",
                ["Author_AlreadyExists"] = "Author with this name already exists.",
                ["Book_Title"]           = "Title",
                ["Book_Cover"]           = "Cover (optional)",
                ["Book_AddTitle"]        = "Add Book",
                ["Book_Rename"]          = "Rename",
                ["Book_Delete"]          = "Delete Book",
                ["Book_ConfirmDelete"]   = "Are you sure you want to delete this book?",
                ["Book_Author"]          = "Author",
                ["Book_Type"]            = "Type: Book",
                ["Book_DateAdded"]       = "Added",
                ["Book_NewTitle"]        = "New title",
                ["Book_AlreadyExists"]   = "A book with this title already exists.",
                ["Book_SelectFile"]      = "Choose image...",
                ["Book_MissingHint"]     = "Tick “Not owned” if you don't have this book yet — the title can then be left empty",
                ["Book_TitlePlaceholder"] = "Book title",
                ["Book_OrderPlaceholder"] = "Leave empty — adds to the end",
                ["Series_Name"]          = "Series Name",
                ["Series_AddTitle"]      = "Add Series",
                ["Series_Rename"]        = "Rename",
                ["Series_Delete"]        = "Delete Series",
                ["Series_ConfirmDelete"] = "Are you sure you want to delete this series?",
                ["Series_Type"]          = "Type: Series",
                ["Series_Parts"]         = "Parts",
                ["Series_Part"]          = "Part",
                ["Series_PartsOptional"] = "Parts (optional)",
                ["Series_AddBook"]       = "Add Book to Series",
                ["Series_BookOrder"]     = "Position in series (optional)",
                ["Series_AddPart"]       = "Add Part",
                ["Series_Author"]        = "Author",
                ["Series_NewName"]       = "New name",
                ["Series_AlreadyExists"] = "A series with this name already exists.",
                ["Series_Cover"]         = "Series Cover (optional)",
                ["Series_NamePlaceholder"] = "Series name",
                ["Trash_Title"]          = "Trash",
                ["Trash_Empty"]          = "Trash is empty.",
                ["Trash_Clear"]          = "Clear Trash",
                ["Trash_ConfirmClear"]   = "Are you sure you want to permanently clear the trash?",
                ["Trash_Restore"]        = "Restore",
                ["Trash_DeleteForever"]  = "Delete Forever",
                ["Trash_Author"]         = "Author",
                ["Trash_Deleted"]        = "Deleted",
                ["Trash_AlreadyExists_Author"]  = "Cannot restore: author \"{0}\" already exists.",
                ["Trash_AlreadyExists_Series"]  = "Cannot restore: series \"{0}\" already exists for this author.",
                ["Trash_AlreadyExists_Book"]    = "Cannot restore: book \"{0}\" already exists for this author.",
                ["Trash_NoParentAuthor"]        = "Cannot restore: the parent author was also deleted.",
                ["History_Title"]        = "History",
                ["History_Empty"]        = "No actions recorded yet.",
                ["History_Clear"]        = "Clear History",
                ["History_ConfirmClear"] = "Are you sure you want to clear the history?",
                ["Hist_AuthorAdded"]     = "Author added: {0}",
                ["Hist_AuthorDeleted"]   = "Author deleted: {0} (with all books and series)",
                ["Hist_AuthorPhoto"]     = "Photo updated for author: {0}",
                ["Hist_BookAdded"]       = "Book added: \"{0}\" by {1}",
                ["Hist_BookAddedSeries"] = "Book added: \"{0}\" by {1} (series: {2})",
                ["Hist_BookDeleted"]     = "Book deleted: \"{0}\" by {1}",
                ["Hist_BookDeletedSeries"] = "Book deleted: \"{0}\" by {1} (series: {2})",
                ["Hist_BookRenamed"]     = "Book renamed: \"{0}\" → \"{1}\" by {2}",
                ["Hist_BookRenamedSeries"] = "Book renamed: \"{0}\" → \"{1}\" by {2} (series: {3})",
                ["Hist_BookCover"]       = "Cover updated for book: \"{0}\" by {1}",
                ["Hist_SeriesAdded"]     = "Series added: \"{0}\" by {1}",
                ["Hist_SeriesDeleted"]   = "Series deleted: \"{0}\" by {1} (with all books)",
                ["Hist_SeriesRenamed"]   = "Series renamed: \"{0}\" → \"{1}\" by {2}",
                ["Hist_SeriesCover"]     = "Cover updated for series: \"{0}\" by {1}",
                ["Hist_Restored"]        = "Restored from trash: {0} \"{1}\"",
                ["Hist_TrashCleared"]    = "Trash cleared",
                ["Hist_HistoryCleared"]  = "History cleared",
                ["Missing_Title"]        = "Missing Books",
                ["Missing_Empty"]        = "No missing books found. All series are complete!",
                ["Missing_Author"]       = "Author",
                ["Missing_Series"]       = "Series",
                ["Missing_Order"]        = "Position in series",
                ["Missing_Hint"]         = "Books marked “Not owned” in any series appear here.",
                ["Missing_Badge"]        = "Not owned",
                ["NotFound_Title"]       = "Page not found",
                ["NotFound_Text"]        = "The book, series or author may have been deleted, or the link is out of date.",
                ["Session_Expired"]      = "Your session has expired. Please sign in again.",
                ["Error_NotFound"]       = "Item not found. It may have been deleted.",
                ["Error_Unknown"]        = "Something went wrong. Please try again.",
                ["Error_Network"]        = "Network error. Please try again.",
                ["Error_Validation"]     = "Some fields are filled in incorrectly.",
                ["Error_NoImage"]        = "Choose an image (jpg, png, gif, webp or bmp).",
                ["Error_TitleRequired"]  = "Enter a title.",
                ["Error_SeriesNameRequired"] = "Enter the series name.",
                ["Author_NameRequired"]  = "Enter the author's name.",
                ["Error_MissingNotFavorite"] = "A book you don't own can't be added to favourites.",
                ["Trash_NoParentSeries"] = "Cannot restore: the book's series was also deleted.",
                ["Toast_AuthorAdded"]    = "Author added",
                ["Toast_BookAdded"]      = "Book added",
                ["Toast_SeriesAdded"]    = "Series added",
                ["Toast_Renamed"]        = "Name saved",
                ["Toast_CoverUpdated"]   = "Cover updated",
                ["Toast_PhotoUpdated"]   = "Photo updated",
                ["Toast_MovedToTrash"]   = "Moved to trash",
                ["Toast_Restored"]       = "Restored",
                ["Toast_DeletedForever"] = "Deleted permanently",
                ["Toast_TrashCleared"]   = "Trash cleared",
                ["Toast_HistoryCleared"] = "History cleared",
                ["Cover_Add"]            = "Add cover",
                ["Cover_Change"]         = "Click to change the cover",
                ["Photo_Add"]            = "Add photo",
                ["Photo_Change"]         = "Click to change the photo",
                ["Series_NoBooks"]       = "No books yet.",
                ["Error_Title"]          = "Something went wrong",
                ["Error_Text"]           = "An unexpected error occurred. Please try again or return to the catalogue.",
                ["Error_Back"]           = "Back to the catalogue",
                ["Storage_ErrorTitle"]   = "The library is temporarily unavailable",
                ["Storage_ErrorText"]    = "The data files (library.json, trash.json, history.json) and their backups could not be read. To protect your data, the application has stopped working with them.",
                ["Storage_ErrorHint"]    = "Check the files in the Data folder and the server log, then restart the application.",
                ["Book_Untitled"]        = "Untitled book",
                ["Book_MissingNeedsTitle"] = "Give the book a title first.",
                ["Book_IsMissing"]       = "Not owned",
                ["Book_IsMissingHint"]   = "The book belongs to the series but isn't in your library.",
                ["Nav_Favorites"]        = "Favourites",
                ["Favorites_Title"]      = "Favourites",
                ["Favorites_Empty"]      = "No favourites yet.",
                ["Favorites_EmptyText"]  = "Tap the heart next to an author, series or book to add it here.",
                ["Favorites_Add"]        = "Add to favourites",
                ["Favorites_Remove"]     = "Remove from favourites",
                ["Nav_Flagged"]          = "Flagged",
                ["Flagged_Title"]        = "Flagged",
                ["Flagged_Empty"]        = "Nothing flagged yet.",
                ["Flagged_EmptyText"]    = "Set flags on a book or mark a series as ongoing, and it will appear here.",
                ["Flagged_All"]          = "All",
                ["Flag_OneOfSeries"]     = "One of a series",
                ["Flag_Duplicate"]       = "Duplicate",
                ["Flag_ForSale"]         = "For sale",
                ["Flag_OutOfPrint"]      = "Out of print",
                ["Flag_Lent"]            = "Lent out",
                ["Flag_Signed"]          = "Signed",
                ["Flag_PoorCondition"]   = "Poor condition",
                ["Flag_OtherEdition"]    = "Different edition",
                ["Series_Ongoing"]       = "Ongoing",
                ["Series_OngoingSection"] = "Ongoing series",
                ["Series_OngoingHint"]   = "Mark that the series is still being continued",
                ["Book_Flags"]           = "Flags",
                ["Book_Note"]            = "Note",
                ["Book_NotePlaceholder"] = "e.g. only book 3 of 8 is available",
                ["Book_NoteHint"]        = "Available when at least one flag is selected.",
                ["Flags_Saved"]          = "Saved",
                ["Flags_Saving"]         = "Saving…",
                ["Confirm_Title"]        = "Confirm",
                ["Confirm_Cancel"]       = "Cancel",
                ["Confirm_Ok"]           = "Confirm",
                ["Btn_Save"]             = "Save",
                ["Btn_Cancel"]           = "Cancel",
                ["Month_01"] = "Jan", ["Month_02"] = "Feb", ["Month_03"] = "Mar",
                ["Month_04"] = "Apr", ["Month_05"] = "May", ["Month_06"] = "Jun",
                ["Month_07"] = "Jul", ["Month_08"] = "Aug", ["Month_09"] = "Sep",
                ["Month_10"] = "Oct", ["Month_11"] = "Nov", ["Month_12"] = "Dec",
            },

            ["ru"] = new()
            {
                ["Pager_Label"]          = "Страницы",
                ["Pager_Prev"]           = "Назад",
                ["Pager_Next"]           = "Вперёд",
                ["Pager_Info"]           = "{0}–{1} из {2}",
                ["Nav_Logout"]           = "Выйти",
                ["Login_Title"]          = "Вход",
                ["Login_Username"]       = "Логин",
                ["Login_Password"]       = "Пароль",
                ["Login_Remember"]       = "Запомнить меня",
                ["Login_Submit"]         = "Войти",
                ["Login_Invalid"]        = "Неверный логин или пароль.",
                ["Login_LockedOut"]      = "Слишком много неудачных попыток. Попробуйте через {0} мин.",
                ["Login_NotConfigured"]  = "Защита включена, но в protection.json не задан логин или пароль.",
                ["Nav_Catalogue"]        = "Каталог",
                ["Nav_MissingBooks"]     = "Недостающие книги",
                ["Nav_History"]          = "История",
                ["Nav_Trash"]            = "Корзина",
                ["Page_Catalogue"]       = "Каталог",
                ["Btn_AddAuthor"]        = "Добавить автора",
                ["Stat_Authors"]         = "Авторы",
                ["Stat_Series"]          = "Серии",
                ["Stat_Books"]           = "Книги",
                ["Btn_BackToTop"]        = "Наверх",
                ["Search_Placeholder"]   = "Поиск авторов, книг, серий...",
                ["Search_Results"]       = "Результаты поиска",
                ["Search_NoResults"]     = "Ничего не найдено по запросу",
                ["Catalogue_Empty"]      = "Каталог пуст. Добавьте первого автора!",
                ["Label_Author"]         = "Автор",
                ["Label_Series"]         = "Серия",
                ["Label_Book"]           = "Книга",
                ["Author_AddTitle"]      = "Добавить автора",
                ["Author_Name"]          = "Имя",
                ["Author_Photo"]         = "Фото (необязательно)",
                ["Author_DateAdded"]     = "Добавлен",
                ["Author_Books"]         = "Книги",
                ["Author_Series"]        = "Серии",
                ["Author_Delete"]        = "Удалить автора",
                ["Author_AddBook"]       = "Добавить книгу",
                ["Author_AddSeries"]     = "Добавить серию",
                ["Author_NoBooksOrSeries"] = "Пока нет книг или серий.",
                ["Author_ConfirmDelete"] = "Вы уверены, что хотите удалить этого автора?",
                ["Author_AlreadyExists"] = "Автор с таким именем уже существует.",
                ["Book_Title"]           = "Название",
                ["Book_Cover"]           = "Обложка (необязательно)",
                ["Book_AddTitle"]        = "Добавить книгу",
                ["Book_Rename"]          = "Переименовать",
                ["Book_Delete"]          = "Удалить книгу",
                ["Book_ConfirmDelete"]   = "Вы уверены, что хотите удалить эту книгу?",
                ["Book_Author"]          = "Автор",
                ["Book_Type"]            = "Тип: Книга",
                ["Book_DateAdded"]       = "Добавлена",
                ["Book_NewTitle"]        = "Новое название",
                ["Book_AlreadyExists"]   = "Книга с таким названием уже существует.",
                ["Book_SelectFile"]      = "Выбрать изображение...",
                ["Book_MissingHint"]     = "Отметьте «Нет в наличии», если книги у вас нет — тогда название можно не указывать",
                ["Book_TitlePlaceholder"] = "Название книги",
                ["Book_OrderPlaceholder"] = "Пусто — добавится в конец",
                ["Series_Name"]          = "Название серии",
                ["Series_AddTitle"]      = "Добавить серию",
                ["Series_Rename"]        = "Переименовать",
                ["Series_Delete"]        = "Удалить серию",
                ["Series_ConfirmDelete"] = "Вы уверены, что хотите удалить эту серию?",
                ["Series_Type"]          = "Тип: Серия",
                ["Series_Parts"]         = "Части",
                ["Series_Part"]          = "Часть",
                ["Series_PartsOptional"] = "Части (необязательно)",
                ["Series_AddBook"]       = "Добавить книгу в серию",
                ["Series_BookOrder"]     = "Позиция в серии (необязательно)",
                ["Series_AddPart"]       = "Добавить часть",
                ["Series_Author"]        = "Автор",
                ["Series_NewName"]       = "Новое название",
                ["Series_AlreadyExists"] = "Серия с таким названием уже существует.",
                ["Series_Cover"]         = "Обложка серии (необязательно)",
                ["Series_NamePlaceholder"] = "Название серии",
                ["Trash_Title"]          = "Корзина",
                ["Trash_Empty"]          = "Корзина пуста.",
                ["Trash_Clear"]          = "Очистить корзину",
                ["Trash_ConfirmClear"]   = "Вы уверены, что хотите полностью очистить корзину?",
                ["Trash_Restore"]        = "Восстановить",
                ["Trash_DeleteForever"]  = "Удалить навсегда",
                ["Trash_Author"]         = "Автор",
                ["Trash_Deleted"]        = "Удалено",
                ["Trash_AlreadyExists_Author"]  = "Невозможно восстановить: автор «{0}» уже существует.",
                ["Trash_AlreadyExists_Series"]  = "Невозможно восстановить: серия «{0}» уже существует у этого автора.",
                ["Trash_AlreadyExists_Book"]    = "Невозможно восстановить: книга «{0}» уже существует у этого автора.",
                ["Trash_NoParentAuthor"]        = "Невозможно восстановить: автор тоже был удалён.",
                ["History_Title"]        = "История",
                ["History_Empty"]        = "Действий пока не было.",
                ["History_Clear"]        = "Очистить историю",
                ["History_ConfirmClear"] = "Вы уверены, что хотите очистить историю?",
                ["Hist_AuthorAdded"]     = "Добавлен автор: {0}",
                ["Hist_AuthorDeleted"]   = "Удалён автор: {0} (со всеми книгами и сериями)",
                ["Hist_AuthorPhoto"]     = "Обновлено фото автора: {0}",
                ["Hist_BookAdded"]       = "Добавлена книга: «{0}» — {1}",
                ["Hist_BookAddedSeries"] = "Добавлена книга: «{0}» — {1} (серия: {2})",
                ["Hist_BookDeleted"]     = "Удалена книга: «{0}» — {1}",
                ["Hist_BookDeletedSeries"] = "Удалена книга: «{0}» — {1} (серия: {2})",
                ["Hist_BookRenamed"]     = "Переименована книга: «{0}» → «{1}» — {2}",
                ["Hist_BookRenamedSeries"] = "Переименована книга: «{0}» → «{1}» — {2} (серия: {3})",
                ["Hist_BookCover"]       = "Обновлена обложка книги: «{0}» — {1}",
                ["Hist_SeriesAdded"]     = "Добавлена серия: «{0}» — {1}",
                ["Hist_SeriesDeleted"]   = "Удалена серия: «{0}» — {1} (со всеми книгами)",
                ["Hist_SeriesRenamed"]   = "Переименована серия: «{0}» → «{1}» — {2}",
                ["Hist_SeriesCover"]     = "Обновлена обложка серии: «{0}» — {1}",
                ["Hist_Restored"]        = "Восстановлено из корзины: {0} «{1}»",
                ["Hist_TrashCleared"]    = "Корзина очищена",
                ["Hist_HistoryCleared"]  = "История очищена",
                ["Missing_Title"]        = "Недостающие книги",
                ["Missing_Empty"]        = "Недостающих книг нет. Все серии полные!",
                ["Missing_Author"]       = "Автор",
                ["Missing_Series"]       = "Серия",
                ["Missing_Order"]        = "Позиция в серии",
                ["Missing_Hint"]         = "Здесь собраны книги из серий, отмеченные «Нет в наличии».",
                ["Missing_Badge"]        = "Нет в наличии",
                ["NotFound_Title"]       = "Страница не найдена",
                ["NotFound_Text"]        = "Возможно, книга, серия или автор были удалены, или ссылка устарела.",
                ["Session_Expired"]      = "Сеанс истёк. Войдите снова.",
                ["Error_NotFound"]       = "Объект не найден. Возможно, он уже удалён.",
                ["Error_Unknown"]        = "Что-то пошло не так. Попробуйте ещё раз.",
                ["Error_Network"]        = "Ошибка сети. Попробуйте ещё раз.",
                ["Error_Validation"]     = "Некоторые поля заполнены неверно.",
                ["Error_NoImage"]        = "Выберите изображение (jpg, png, gif, webp или bmp).",
                ["Error_TitleRequired"]  = "Введите название.",
                ["Error_SeriesNameRequired"] = "Введите название серии.",
                ["Author_NameRequired"]  = "Введите имя автора.",
                ["Error_MissingNotFavorite"] = "Книгу, которой нет в наличии, нельзя добавить в избранное.",
                ["Trash_NoParentSeries"] = "Нельзя восстановить: серия этой книги тоже удалена.",
                ["Toast_AuthorAdded"]    = "Автор добавлен",
                ["Toast_BookAdded"]      = "Книга добавлена",
                ["Toast_SeriesAdded"]    = "Серия добавлена",
                ["Toast_Renamed"]        = "Название сохранено",
                ["Toast_CoverUpdated"]   = "Обложка обновлена",
                ["Toast_PhotoUpdated"]   = "Фото обновлено",
                ["Toast_MovedToTrash"]   = "Перемещено в корзину",
                ["Toast_Restored"]       = "Восстановлено",
                ["Toast_DeletedForever"] = "Удалено навсегда",
                ["Toast_TrashCleared"]   = "Корзина очищена",
                ["Toast_HistoryCleared"] = "История очищена",
                ["Cover_Add"]            = "Добавить обложку",
                ["Cover_Change"]         = "Нажмите, чтобы сменить обложку",
                ["Photo_Add"]            = "Добавить фото",
                ["Photo_Change"]         = "Нажмите, чтобы сменить фото",
                ["Series_NoBooks"]       = "Книг пока нет.",
                ["Error_Title"]          = "Что-то пошло не так",
                ["Error_Text"]           = "Произошла непредвиденная ошибка. Попробуйте ещё раз или вернитесь в каталог.",
                ["Error_Back"]           = "Вернуться в каталог",
                ["Storage_ErrorTitle"]   = "Библиотека временно недоступна",
                ["Storage_ErrorText"]    = "Не удалось прочитать файлы данных (library.json, trash.json, history.json) и их резервные копии. Чтобы не повредить данные, приложение приостановило работу с ними.",
                ["Storage_ErrorHint"]    = "Проверьте файлы в папке Data и журнал сервера, затем перезапустите приложение.",
                ["Book_Untitled"]        = "Книга без названия",
                ["Book_MissingNeedsTitle"] = "Сначала дайте книге название.",
                ["Book_IsMissing"]       = "Нет в наличии",
                ["Book_IsMissingHint"]   = "Книга есть в серии, но её нет в вашей библиотеке.",
                ["Nav_Favorites"]        = "Избранное",
                ["Favorites_Title"]      = "Избранное",
                ["Favorites_Empty"]      = "В избранном пока пусто.",
                ["Favorites_EmptyText"]  = "Нажмите на сердечко у автора, серии или книги, чтобы добавить их сюда.",
                ["Favorites_Add"]        = "Добавить в избранное",
                ["Favorites_Remove"]     = "Убрать из избранного",
                ["Nav_Flagged"]          = "Отмеченные",
                ["Flagged_Title"]        = "Отмеченные",
                ["Flagged_Empty"]        = "Пока ничего не отмечено.",
                ["Flagged_EmptyText"]    = "Поставьте флажок на книгу или отметьте, что серия продолжается, — и она появится здесь.",
                ["Flagged_All"]          = "Все",
                ["Flag_OneOfSeries"]     = "Одна из серии",
                ["Flag_Duplicate"]       = "Дубликат",
                ["Flag_ForSale"]         = "На продажу",
                ["Flag_OutOfPrint"]      = "Нет в продаже",
                ["Flag_Lent"]            = "Одолжена",
                ["Flag_Signed"]          = "С автографом",
                ["Flag_PoorCondition"]   = "Плохое состояние",
                ["Flag_OtherEdition"]    = "Другое издание",
                ["Series_Ongoing"]       = "Продолжается",
                ["Series_OngoingSection"] = "Продолжающиеся серии",
                ["Series_OngoingHint"]   = "Отметить, что серия ещё продолжается",
                ["Book_Flags"]           = "Флажки",
                ["Book_Note"]            = "Описание",
                ["Book_NotePlaceholder"] = "например: в наличии только 3-я книга из 8",
                ["Book_NoteHint"]        = "Доступно, если выбран хотя бы один флажок.",
                ["Flags_Saved"]          = "Сохранено",
                ["Flags_Saving"]         = "Сохранение…",
                ["Confirm_Title"]        = "Подтверждение",
                ["Confirm_Cancel"]       = "Отмена",
                ["Confirm_Ok"]           = "Подтвердить",
                ["Btn_Save"]             = "Сохранить",
                ["Btn_Cancel"]           = "Отмена",
                ["Month_01"] = "янв", ["Month_02"] = "фев", ["Month_03"] = "мар",
                ["Month_04"] = "апр", ["Month_05"] = "май", ["Month_06"] = "июн",
                ["Month_07"] = "июл", ["Month_08"] = "авг", ["Month_09"] = "сен",
                ["Month_10"] = "окт", ["Month_11"] = "ноя", ["Month_12"] = "дек",
            },

            ["pl"] = new()
            {
                ["Pager_Label"]          = "Strony",
                ["Pager_Prev"]           = "Wstecz",
                ["Pager_Next"]           = "Dalej",
                ["Pager_Info"]           = "{0}–{1} z {2}",
                ["Nav_Logout"]           = "Wyloguj",
                ["Login_Title"]          = "Logowanie",
                ["Login_Username"]       = "Login",
                ["Login_Password"]       = "Hasło",
                ["Login_Remember"]       = "Zapamiętaj mnie",
                ["Login_Submit"]         = "Zaloguj",
                ["Login_Invalid"]        = "Nieprawidłowy login lub hasło.",
                ["Login_LockedOut"]      = "Zbyt wiele nieudanych prób. Spróbuj ponownie za {0} min.",
                ["Login_NotConfigured"]  = "Ochrona jest włączona, ale w protection.json nie ustawiono loginu ani hasła.",
                ["Nav_Catalogue"]        = "Katalog",
                ["Nav_MissingBooks"]     = "Brakujące książki",
                ["Nav_History"]          = "Historia",
                ["Nav_Trash"]            = "Kosz",
                ["Page_Catalogue"]       = "Katalog",
                ["Btn_AddAuthor"]        = "Dodaj autora",
                ["Stat_Authors"]         = "Autorzy",
                ["Stat_Series"]          = "Serie",
                ["Stat_Books"]           = "Książki",
                ["Btn_BackToTop"]        = "Na górę",
                ["Search_Placeholder"]   = "Szukaj autorów, książek, serii...",
                ["Search_Results"]       = "Wyniki wyszukiwania",
                ["Search_NoResults"]     = "Nic nie znaleziono dla",
                ["Catalogue_Empty"]      = "Katalog jest pusty. Dodaj pierwszego autora!",
                ["Label_Author"]         = "Autor",
                ["Label_Series"]         = "Seria",
                ["Label_Book"]           = "Książka",
                ["Author_AddTitle"]      = "Dodaj autora",
                ["Author_Name"]          = "Imię i nazwisko",
                ["Author_Photo"]         = "Zdjęcie (opcjonalnie)",
                ["Author_DateAdded"]     = "Dodano",
                ["Author_Books"]         = "Książki",
                ["Author_Series"]        = "Serie",
                ["Author_Delete"]        = "Usuń autora",
                ["Author_AddBook"]       = "Dodaj książkę",
                ["Author_AddSeries"]     = "Dodaj serię",
                ["Author_NoBooksOrSeries"] = "Brak książek lub serii.",
                ["Author_ConfirmDelete"] = "Czy na pewno chcesz usunąć tego autora?",
                ["Author_AlreadyExists"] = "Autor o tym imieniu już istnieje.",
                ["Book_Title"]           = "Tytuł",
                ["Book_Cover"]           = "Okładka (opcjonalnie)",
                ["Book_AddTitle"]        = "Dodaj książkę",
                ["Book_Rename"]          = "Zmień nazwę",
                ["Book_Delete"]          = "Usuń książkę",
                ["Book_ConfirmDelete"]   = "Czy na pewno chcesz usunąć tę książkę?",
                ["Book_Author"]          = "Autor",
                ["Book_Type"]            = "Typ: Książka",
                ["Book_DateAdded"]       = "Dodano",
                ["Book_NewTitle"]        = "Nowy tytuł",
                ["Book_AlreadyExists"]   = "Książka o takim tytule już istnieje.",
                ["Book_SelectFile"]      = "Wybierz obraz...",
                ["Book_MissingHint"]     = "Zaznacz «Brak w kolekcji», jeśli nie masz tej książki — wtedy tytuł można pominąć",
                ["Book_TitlePlaceholder"] = "Tytuł książki",
                ["Book_OrderPlaceholder"] = "Puste — dodaje na końcu",
                ["Series_Name"]          = "Nazwa serii",
                ["Series_AddTitle"]      = "Dodaj serię",
                ["Series_Rename"]        = "Zmień nazwę",
                ["Series_Delete"]        = "Usuń serię",
                ["Series_ConfirmDelete"] = "Czy na pewno chcesz usunąć tę serię?",
                ["Series_Type"]          = "Typ: Seria",
                ["Series_Parts"]         = "Części",
                ["Series_Part"]          = "Część",
                ["Series_PartsOptional"] = "Części (opcjonalnie)",
                ["Series_AddBook"]       = "Dodaj książkę do serii",
                ["Series_BookOrder"]     = "Pozycja w serii (opcjonalnie)",
                ["Series_AddPart"]       = "Dodaj część",
                ["Series_Author"]        = "Autor",
                ["Series_NewName"]       = "Nowa nazwa",
                ["Series_AlreadyExists"] = "Seria o takiej nazwie już istnieje.",
                ["Series_Cover"]         = "Okładka serii (opcjonalnie)",
                ["Series_NamePlaceholder"] = "Nazwa serii",
                ["Trash_Title"]          = "Kosz",
                ["Trash_Empty"]          = "Kosz jest pusty.",
                ["Trash_Clear"]          = "Opróżnij kosz",
                ["Trash_ConfirmClear"]   = "Czy na pewno chcesz opróżnić kosz?",
                ["Trash_Restore"]        = "Przywróć",
                ["Trash_DeleteForever"]  = "Usuń na zawsze",
                ["Trash_Author"]         = "Autor",
                ["Trash_Deleted"]        = "Usunięto",
                ["Trash_AlreadyExists_Author"]  = "Nie można przywrócić: autor «{0}» już istnieje.",
                ["Trash_AlreadyExists_Series"]  = "Nie można przywrócić: seria «{0}» już istnieje dla tego autora.",
                ["Trash_AlreadyExists_Book"]    = "Nie można przywrócić: książka «{0}» już istnieje dla tego autora.",
                ["Trash_NoParentAuthor"]        = "Nie można przywrócić: autor również został usunięty.",
                ["History_Title"]        = "Historia",
                ["History_Empty"]        = "Brak zapisanych działań.",
                ["History_Clear"]        = "Wyczyść historię",
                ["History_ConfirmClear"] = "Czy na pewno chcesz wyczyścić historię?",
                ["Hist_AuthorAdded"]     = "Dodano autora: {0}",
                ["Hist_AuthorDeleted"]   = "Usunięto autora: {0} (z wszystkimi książkami i seriami)",
                ["Hist_AuthorPhoto"]     = "Zaktualizowano zdjęcie autora: {0}",
                ["Hist_BookAdded"]       = "Dodano książkę: «{0}» — {1}",
                ["Hist_BookAddedSeries"] = "Dodano książkę: «{0}» — {1} (seria: {2})",
                ["Hist_BookDeleted"]     = "Usunięto książkę: «{0}» — {1}",
                ["Hist_BookDeletedSeries"] = "Usunięto książkę: «{0}» — {1} (seria: {2})",
                ["Hist_BookRenamed"]     = "Zmieniono nazwę książki: «{0}» → «{1}» — {2}",
                ["Hist_BookRenamedSeries"] = "Zmieniono nazwę książki: «{0}» → «{1}» — {2} (seria: {3})",
                ["Hist_BookCover"]       = "Zaktualizowano okładkę książki: «{0}» — {1}",
                ["Hist_SeriesAdded"]     = "Dodano serię: «{0}» — {1}",
                ["Hist_SeriesDeleted"]   = "Usunięto serię: «{0}» — {1} (z wszystkimi książkami)",
                ["Hist_SeriesRenamed"]   = "Zmieniono nazwę serii: «{0}» → «{1}» — {2}",
                ["Hist_SeriesCover"]     = "Zaktualizowano okładkę serii: «{0}» — {1}",
                ["Hist_Restored"]        = "Przywrócono z kosza: {0} «{1}»",
                ["Hist_TrashCleared"]    = "Kosz opróżniony",
                ["Hist_HistoryCleared"]  = "Historia wyczyszczona",
                ["Missing_Title"]        = "Brakujące książki",
                ["Missing_Empty"]        = "Brak brakujących książek. Wszystkie serie są kompletne!",
                ["Missing_Author"]       = "Autor",
                ["Missing_Series"]       = "Seria",
                ["Missing_Order"]        = "Pozycja w serii",
                ["Missing_Hint"]         = "Tutaj trafiają książki z serii oznaczone «Brak w kolekcji».",
                ["Missing_Badge"]        = "Brak w kolekcji",
                ["NotFound_Title"]       = "Nie znaleziono strony",
                ["NotFound_Text"]        = "Książka, seria lub autor mogły zostać usunięte albo link jest nieaktualny.",
                ["Session_Expired"]      = "Sesja wygasła. Zaloguj się ponownie.",
                ["Error_NotFound"]       = "Nie znaleziono elementu. Mógł zostać usunięty.",
                ["Error_Unknown"]        = "Coś poszło nie tak. Spróbuj ponownie.",
                ["Error_Network"]        = "Błąd sieci. Spróbuj ponownie.",
                ["Error_Validation"]     = "Niektóre pola są wypełnione niepoprawnie.",
                ["Error_NoImage"]        = "Wybierz obraz (jpg, png, gif, webp lub bmp).",
                ["Error_TitleRequired"]  = "Podaj tytuł.",
                ["Error_SeriesNameRequired"] = "Podaj nazwę serii.",
                ["Author_NameRequired"]  = "Podaj imię i nazwisko autora.",
                ["Error_MissingNotFavorite"] = "Książki spoza kolekcji nie można dodać do ulubionych.",
                ["Trash_NoParentSeries"] = "Nie można przywrócić: seria tej książki również została usunięta.",
                ["Toast_AuthorAdded"]    = "Autor dodany",
                ["Toast_BookAdded"]      = "Książka dodana",
                ["Toast_SeriesAdded"]    = "Seria dodana",
                ["Toast_Renamed"]        = "Nazwa zapisana",
                ["Toast_CoverUpdated"]   = "Okładka zaktualizowana",
                ["Toast_PhotoUpdated"]   = "Zdjęcie zaktualizowane",
                ["Toast_MovedToTrash"]   = "Przeniesiono do kosza",
                ["Toast_Restored"]       = "Przywrócono",
                ["Toast_DeletedForever"] = "Usunięto na zawsze",
                ["Toast_TrashCleared"]   = "Kosz opróżniony",
                ["Toast_HistoryCleared"] = "Historia wyczyszczona",
                ["Cover_Add"]            = "Dodaj okładkę",
                ["Cover_Change"]         = "Kliknij, aby zmienić okładkę",
                ["Photo_Add"]            = "Dodaj zdjęcie",
                ["Photo_Change"]         = "Kliknij, aby zmienić zdjęcie",
                ["Series_NoBooks"]       = "Brak książek.",
                ["Error_Title"]          = "Coś poszło nie tak",
                ["Error_Text"]           = "Wystąpił nieoczekiwany błąd. Spróbuj ponownie lub wróć do katalogu.",
                ["Error_Back"]           = "Wróć do katalogu",
                ["Storage_ErrorTitle"]   = "Biblioteka jest chwilowo niedostępna",
                ["Storage_ErrorText"]    = "Nie udało się odczytać plików danych (library.json, trash.json, history.json) ani ich kopii zapasowych. Aby nie uszkodzić danych, aplikacja wstrzymała pracę z nimi.",
                ["Storage_ErrorHint"]    = "Sprawdź pliki w folderze Data i dziennik serwera, a następnie uruchom aplikację ponownie.",
                ["Book_Untitled"]        = "Książka bez tytułu",
                ["Book_MissingNeedsTitle"] = "Najpierw nadaj książce tytuł.",
                ["Book_IsMissing"]       = "Brak w kolekcji",
                ["Book_IsMissingHint"]   = "Książka należy do serii, ale nie ma jej w Twojej bibliotece.",
                ["Nav_Favorites"]        = "Ulubione",
                ["Favorites_Title"]      = "Ulubione",
                ["Favorites_Empty"]      = "Nie masz jeszcze ulubionych.",
                ["Favorites_EmptyText"]  = "Kliknij serce przy autorze, serii lub książce, aby dodać je tutaj.",
                ["Favorites_Add"]        = "Dodaj do ulubionych",
                ["Favorites_Remove"]     = "Usuń z ulubionych",
                ["Nav_Flagged"]          = "Oznaczone",
                ["Flagged_Title"]        = "Oznaczone",
                ["Flagged_Empty"]        = "Nic jeszcze nie oznaczono.",
                ["Flagged_EmptyText"]    = "Dodaj flagę do książki lub oznacz serię jako kontynuowaną, a pojawi się tutaj.",
                ["Flagged_All"]          = "Wszystkie",
                ["Flag_OneOfSeries"]     = "Jedna z serii",
                ["Flag_Duplicate"]       = "Duplikat",
                ["Flag_ForSale"]         = "Na sprzedaż",
                ["Flag_OutOfPrint"]      = "Niedostępna w sprzedaży",
                ["Flag_Lent"]            = "Pożyczona",
                ["Flag_Signed"]          = "Z autografem",
                ["Flag_PoorCondition"]   = "Zły stan",
                ["Flag_OtherEdition"]    = "Inne wydanie",
                ["Series_Ongoing"]       = "W toku",
                ["Series_OngoingSection"] = "Serie w toku",
                ["Series_OngoingHint"]   = "Oznacz, że seria jest nadal kontynuowana",
                ["Book_Flags"]           = "Flagi",
                ["Book_Note"]            = "Opis",
                ["Book_NotePlaceholder"] = "np. dostępna tylko 3. książka z 8",
                ["Book_NoteHint"]        = "Dostępne, gdy wybrano co najmniej jedną flagę.",
                ["Flags_Saved"]          = "Zapisano",
                ["Flags_Saving"]         = "Zapisywanie…",
                ["Confirm_Title"]        = "Potwierdź",
                ["Confirm_Cancel"]       = "Anuluj",
                ["Confirm_Ok"]           = "Potwierdź",
                ["Btn_Save"]             = "Zapisz",
                ["Btn_Cancel"]           = "Anuluj",
                ["Month_01"] = "sty", ["Month_02"] = "lut", ["Month_03"] = "mar",
                ["Month_04"] = "kwi", ["Month_05"] = "maj", ["Month_06"] = "cze",
                ["Month_07"] = "lip", ["Month_08"] = "sie", ["Month_09"] = "wrz",
                ["Month_10"] = "paź", ["Month_11"] = "lis", ["Month_12"] = "gru",
            }
        };

        public LocalizationService(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        public string CurrentCulture
        {
            get
            {
                var langCookie = _httpContextAccessor.HttpContext?.Request.Cookies["lang"];
                if (!string.IsNullOrEmpty(langCookie) && _translations.ContainsKey(langCookie))
                    return langCookie;

                var aspCookie = _httpContextAccessor.HttpContext?.Request.Cookies[".AspNetCore.Culture"];
                if (aspCookie != null)
                {
                    var uicPart = aspCookie.Split('|')
                        .FirstOrDefault(p => p.StartsWith("uic="))
                        ?.Replace("uic=", "");
                    if (!string.IsNullOrEmpty(uicPart) && _translations.ContainsKey(uicPart))
                        return uicPart;
                }
                return "en";
            }
        }

        public string this[string key]
        {
            get
            {
                var culture = CurrentCulture;
                if (_translations.TryGetValue(culture, out var dict) &&
                    dict.TryGetValue(key, out var value))
                    return value;
                if (_translations["en"].TryGetValue(key, out var fallback))
                    return fallback;
                return key;
            }
        }

        public string BookTitle(string? title) =>
            string.IsNullOrWhiteSpace(title) ? this["Book_Untitled"] : title;

        public string FormatDate(DateTime dt)
        {
            var month = this[$"Month_{dt.Month:D2}"];
            return $"{dt.Day:D2} {month} {dt.Year}";
        }
    }
}
